### ISSUE TITLE
Add a "Mesh List "socket  

### ISSUE THREAD

**Issue by kdsin23** [3DSinghVFX/animation_nodes#144]
is it possible to add a "MeshList" output?
![mesh list](https://user-images.githubusercontent.com/64368228/80739217-a75cbb80-8b48-11ea-90ae-4ae90f8420b5.png)

**Comment by 3DSinghVFX** [comment]
Do you want a mesh list from the object list with the _Create Object List_ node?

**Comment by Gerstmann-Bradley** [comment]
i think more useful way is to vectorize the "mesh object input" node.
Otherwise when it comes a collection, the same issue will occur.

**Comment by 3DSinghVFX** [comment]
> i think more useful way is to vectorize the "object mesh data" node.

@Gerstmann-Bradley Hi :) Actually, the problem is _Mesh Object Input_ gives _mesh_ but also outputs _vertices, polygons indices, edges_, etc of the same mesh. So, it is difficult to vectorized the _Mesh Object Input_ node.

**Comment by Gerstmann-Bradley** [comment]
> > i think more useful way is to vectorize the "object mesh data" node.
> 
> @Gerstmann-Bradley Hi :) Actually, the problem is _Mesh Object Input_ gives _mesh_ but also outputs _vertices, polygons indices, edges_, etc of the same mesh. So, it is difficult to vectorized the _Mesh Object Input_ node.

Seems a rough question, I don't know. I usually solve it with a loop to only output a mesh list.
Join mesh list node outside the loop helps make it into a single mesh.
And mesh info node helps to get all these data you mentioned above.
If upon vectorization, I only ask for an output of "mesh list" or "a joined single mesh", will it make your task easier? I don't think in that case it will be more difficult than output a mesh list in this "create object list" node? I am not a coder so I don't know.

My point is that, by any chance, if this topic is going to be continued/considered, instead of output "mesh list" in this "create object list" node, vectorizing "mesh object input" node definitely looks more reasonable and useful.

**Comment by 3DSinghVFX** [comment]
> 
> Seems a rough question, I don't know. I usually solve it with a loop to only output a mesh list.
> Join mesh list node outside the loop helps make it into a single mesh.
> And mesh info node helps to get all these data you mentioned above.
> If upon vectorization, I only ask for an output of "mesh list" or "a joined single mesh", will it make your task easier? I don't think in that case it will be more difficult than output a mesh list in this "create object list" node? I am not a coder so I don't know. 

@Gerstmann-Bradley  It is a significant difference in the _Mesh Object Input_ and _Mesh Info_ nodes, and at the code level, it is not straight forward. We have to take care of all the outputs of _Mesh Object Input_ in the _Mesh Info_ node.

![Screenshot from 2020-05-01 11-03-43](https://user-images.githubusercontent.com/30294746/80784941-4a8af080-8b9c-11ea-8043-51dbe789c96c.png)

I think _Create Object List node + Loop node (Mesh Object Input node)_ is an easy and simple solution.

**Comment by 3DSinghVFX** [comment]
> 
> Seems a rough question, I don't know. I usually solve it with a loop to only output a mesh list.
> Join mesh list node outside the loop helps make it into a single mesh.
> And mesh info node helps to get all these data you mentioned above.
> If upon vectorization, I only ask for an output of "mesh list" or "a joined single mesh", will it make your task easier? I don't think in that case it will be more difficult than output a mesh list in this "create object list" node? I am not a coder so I don't know. 

@Gerstmann-Bradley  It is a significant difference in the _Mesh Object Input_ and _Mesh Info_ nodes, and at the code level, it is not straight forward. We have to take care of all the outputs of _Mesh Object Input_ in the _Mesh Info_ node.

![Screenshot from 2020-05-01 11-03-43](https://user-images.githubusercontent.com/30294746/80784941-4a8af080-8b9c-11ea-8043-51dbe789c96c.png)

**Comment by kdsin23** [comment]
> Do you want a mesh list from the object list with the _Create Object List_ node?

Thank you! yes,I want to generate a mesh list from the object list if possible.
![mesh list var](https://user-images.githubusercontent.com/64368228/80788557-03acf300-8bbc-11ea-826f-c76785dbceeb.png)

using transform mesh node can clone a mesh,but want to clone all sorts of mesh needs some mesh list,using loop to generate mesh list sometimes it calclute too slow, what do you think about it?

**Comment by 3DSinghVFX** [comment]
The _Transform Mesh_ node can take _mesh_ or _mesh list_. If you have dense mesh then _Mesh Object Input_ may calculate slow. Otherwise, it is very fast and optimizes, (`~5.2ms` in this example): 
![Screenshot from 2020-05-01 13-01-02](https://user-images.githubusercontent.com/30294746/80790393-567eae80-8bac-11ea-935e-894987b9214b.png)

It is not easy as I have explained. However, even if I add that functionality, we have to run the same code under the hood.

**Comment by kdsin23** [comment]
> The _Transform Mesh_ node can take _mesh_ or _mesh list_. If you have dense mesh then _Mesh Object Input_ may calculate slow. Otherwise, it is very fast and optimizes, (`~5.2ms` in this example):
> ![Screenshot from 2020-05-01 13-01-02](https://user-images.githubusercontent.com/30294746/80790393-567eae80-8bac-11ea-935e-894987b9214b.png)
> 
> It is not easy as I have explained. However, even if I add that functionality, we have to run the same code under the hood.

Thank you! I think this topic may be closed.

**Comment by 3DSinghVFX** [comment]
Thanks. Okay I'll close.
