### ISSUE TITLE
"Mesh Islands" mode  be added to "set vertex color" Node

### ISSUE THREAD

**Issue by kdsin23** [3DSinghVFX/animation_nodes#145]
the "set vertex color" node you developed,is it possible to add a "Mesh Islands" mode option,more detail is here 

 `https://github.com/harisreedhar/AN_BLUEFOX/issues/5`

if possible ,that would be great,i think.

**Comment by 3DSinghVFX** [comment]
@kdsin23  Thanks for the info.
- Yes, it is possible. I'm aware of that feature but I'm looking better method so that we have good performance for many mesh-islands. 

- Another feature I would like to add (or keep old) _vertex color_ per mesh during mesh replication (Transform Mesh node).

- A similar proposal for material per mesh-island on AN page: https://github.com/JacquesLucke/animation_nodes/issues/1387

- The same may be for UV maps as well.

**Comment by kdsin23** [comment]
> @kdsin23 Thanks for the info.
> 
>     * Yes, it is possible. I'm aware of that feature but I'm looking better method so that we have good performance for many mesh-islands.
> 
>     * Another feature I would like to add (or keep old) _vertex color_ per mesh during mesh replication (Transform Mesh node).
> 
>     * A similar proposal for material per mesh-island on AN page: [JacquesLucke#1387](https://github.com/JacquesLucke/animation_nodes/issues/1387)
> 
>     * The same may be for UV maps as well.

thank you! looking forward to add this function to the build of AN..
