### ISSUE TITLE
Turning on taper mode causing red bars

### ISSUE THREAD

**Issue by genesis2303** [3DSinghVFX/animation_nodes#169]
It happens every single time I try it, no mater if taper object is connected or not, tried it a few times with different options on/off, and I just wanted to know what this option does. Until curve object output is removed red bars remains (edit, or until I tunrn this socket off or leave it empy). Windows, 2.93, btw does blender have any way to produce some crash report? I'm using your version and don't even think of returning to official, but it crushes quite often, AN stops working really often, and from time to time I get CTD, so maybe I could send some data from time to time somehow?

**Comment by Gerstmann-Bradley** [comment]
A reproducible error. but I think this issue should goes to Omar instead, since curve object output node is added by him in the main branch. And this issue is definitely reproducible in the main branch (confirmed by me).
https://github.com/JacquesLucke/animation_nodes/issues/1679#issuecomment-805138439

As for the crash report in blender windows, please read the manual here for details: https://docs.blender.org/manual/en/latest/troubleshooting/crash.html
As for the crushes, I'm just a user not a developer, but I use AN everyday for nearly every file I'm fine.
Would you be able to elaborate more about your crushes. When did it happen? Like rendering Or?

**Comment by Gerstmann-Bradley** [comment]
I have found that if you updated things to newest 2.93 alpha, there won't be error.
Perhaps it's because in older build of 2.93, there isn't taper mode yet.

**Comment by genesis2303** [comment]
Most often AN stops working when I do test renders not animation but just
single frame, sometimes when I connect some nodes, and very rare unexpected
but this could be just because of alpha I guess. Few times happened with
setup using instancing with GN I guess it is experimental but so light on
performance that I will probably use it anyway in the future.

śr., 14 kwi 2021, 23:27 użytkownik Gerstmann-Bradley <
***@***.***> napisał:

**Comment by Gerstmann-Bradley** [comment]
https://github.com/JacquesLucke/animation_nodes/issues/1679#issuecomment-820268268

Omar fixed earlier.

**Comment by 3DSinghVFX** [comment]
@genesis2303 Thanks. It is fixed https://github.com/3DSinghVFX/animation_nodes/commit/4da592c284398381073f867d447100e11edaab36
