### ISSUE TITLE
How to set the amount of particles?

### ISSUE THREAD

**Issue by clankill3r** [3DSinghVFX/animation_nodes#50]
I have a situation where the amount of particles is changing each frame.
How can I set the amount of particels?

**Comment by 3DSinghVFX** [comment]
Hi...
In the current blender particle-system, we can't animate the total amount of particles which is a limitation.
Here is an example, to set the length of input lists for Particles Output node,
![screen](https://user-images.githubusercontent.com/30294746/71552424-1d2e0a80-2a23-11ea-9d37-afbd07552f65.png)

**Comment by clankill3r** [comment]
The thing is, I have 1000 particles here, but I give only 2 positions, and I only see 2 particles.
And this is exactly what I want!

![particles](https://user-images.githubusercontent.com/738650/71717748-57c7e680-2e19-11ea-8295-1888e0b871a8.png)

But as soon as I add rotations then it does not work.

Can't this line be changed?: (particles_output.py)
` if len(rotations) != 0 and self.rotBool: particles.foreach_set('rotation', self.flatList(rotations))`

Where it set the rotation for the amount of rotations it received instead of the amount of particles?

**Comment by 3DSinghVFX** [comment]
@clankill3r, Actually, under the hood, this node using the foreach_set() function, so we have to provide the position for **all the particles** and the same goes for velocities, die_times, and rotations. Otherwise, it will give a strange behavior. To avoid this confusion, I'll add an error message in this node which will show up when the length of locations list (or any other variables) is less or greater than the total number of particles.

1. Here is an example to set the position of a particle having index zero and Tool-Settings for AN to work for particles, 
![screen](https://user-images.githubusercontent.com/30294746/71724028-ce360a00-2e54-11ea-97c6-fbfb717f0ea8.png)

2. Please watch these videos in which I have explained how to use this node, https://www.youtube.com/watch?v=hvzr8lu5Ef0, and https://www.youtube.com/watch?v=8pvX2_ZH1l0. You can download the example files which are provided in the video description.

3. In the recent version of Blender 2.79c or Blender 2.8x, during loop animation, particle cache does not clear unless you change any particle setting or force setting.

4. To solve this problem, I have written a small script that clears the particle cache at the start frame during loop animation. This script is added to the Particle Input Group node (mentioned in the above videos). I have also made different forces (wind, central, vortex, etc.) group node to control the particles (https://www.youtube.com/watch?v=bAQmewZSJQ4). Here is an example, 
![JUGAADANParticleSystem_AN28_Main_v3](https://user-images.githubusercontent.com/30294746/71724737-5f0de500-2e57-11ea-85fd-006faa8fb4a9.png)

Please let me know if this answers your question.
