### ISSUE TITLE
trim spline after "find shortest path"

### ISSUE THREAD

**Issue by randomuser531** [3DSinghVFX/animation_nodes#84]
Hi, i think you are aware of it, but in case you are not ... when using trim spline after "find shortest Path" and trying to trim from the end, the individual splines get trimmed - all the splines are not treated as one. Using the trim from start all the splines are treated as one. 
![trim Spline](https://user-images.githubusercontent.com/48297111/73272384-92d3f480-41e2-11ea-8af1-e116f0d1cc48.jpg)

there is also an issue when reversing the Vector and Edge-lists to get the effect running (trimming from end), resulting in some weird behaviour but maybe i am doing it wrong ... 
![trim Spline 2](https://user-images.githubusercontent.com/48297111/73272954-800def80-41e3-11ea-9aed-687e746602e4.jpg)

thanks for your work!

**Comment by 3DSinghVFX** [comment]
Hi :)
1. It is working fine as expected. Because those splines are overlapped that why you are seeing that effect. Try trim (end) with a single path.

2. It is not an issue. Reversing the order of vertices will change the order, so their connections to each other. That is the reason you are getting that problem.

I think you want to reverse the trim direction of splines. Here is an example to reverse the spline direction,
![ShortestPath2](https://user-images.githubusercontent.com/30294746/73293829-97bc9680-422a-11ea-8776-4bb9599c34d1.png)

![ShortestPath1](https://user-images.githubusercontent.com/30294746/73293976-e23e1300-422a-11ea-86cb-d49d5d9728fb.png)

Blend File: 
[ShortestPath1.blend.zip](https://github.com/3DSinghVFX/animation_nodes/files/4124004/ShortestPath1.blend.zip)

**Comment by randomuser531** [comment]
thanks!

**Comment by 3DSinghVFX** [comment]
You're welcome :) Should I close the issue?

**Comment by 3DSinghVFX** [comment]
We have added the _Change Spline Direction_ node #99.

I will close this issue for now. Feel free to reopen this if you still experience the problem.
